(require 'lsp-bridge)

(keymap-global-set "C-c l d" #'lsp-bridge-find-def)
(keymap-global-set "C-c l D" #'lsp-bridge-find-def-other-window)
(keymap-global-set "C-c l b" #'lsp-bridge-find-def-return)
(keymap-global-set "C-c l t" #'lsp-bridge-find-type-def)
(keymap-global-set "C-c l T" #'lsp-bridge-find-type-def-other-window)
(keymap-global-set "C-c l i" #'lsp-bridge-find-impl)
(keymap-global-set "C-c l I" #'lsp-bridge-find-impl-other-window)
(keymap-global-set "C-c l r" #'lsp-bridge-find-references)
(keymap-global-set "C-c l h" #'lsp-bridge-popup-documentation)
(keymap-global-set "C-c l r" #'lsp-bridge-rename)
(keymap-global-set "C-c l ]" #'lsp-bridge-diagnostic-jump-next)
(keymap-global-set "C-c l [" #'lsp-bridge-diagnostic-jump-prev)
(keymap-global-set "C-c l e" #'lsp-bridge-diagnostic-list)
(keymap-global-set "C-c l E" #'lsp-bridge-diagnostic-copy)
(keymap-global-set "C-c l a" #'lsp-bridge-code-action)
(keymap-global-set "C-c l s" #'lsp-bridge-toggle-sdcv-helper)

(setq lsp-bridge-single-lang-server-extension-list
      '((("css") . "vscode-css-language-server")
        (("html" "gohtml") . "vscode-html-language-server")))
(setq lsp-bridge-enable-hover-diagnostic t)
(setq acm-enable-quick-access t)
(setq acm-candidate-match-function #'orderless-regexp)
(setq acm-enable-yas nil)
(setq acm-enable-search-file-words nil)
(setq acm-backend-lsp-candidate-min-length 0)
(setq acm-backend-elisp-candidate-min-length 0)
(define-key acm-mode-map [tab] #'acm-insert-common)

(global-lsp-bridge-mode)

(provide 'init-lsp-bridge)
